### PR TITLE
move systemd_%.bbappend content in soletta-demo-systemd-files

### PR DESCRIPTION
**Pull request by mythi**
The systemd_%.bbappend maintained in meta-soletta is primarily about
soletta demo specific .service and configuration files.

Instead of appending to systemd, it is preferred to have a dedicated
recipe that installs the configuration soletta demos need and have that
depend on systemd runtime.

Fixes: #31 

Signed-off-by: Mikko Ylinen mikko.ylinen@intel.com

### CODE REVIEW

**Comment by barbieri** [comment]
okay, but please add "-demo" or "-dev-app" to the name, otherwise it will look like a soletta (lib/framework), which is not the case.

@brunobottazzini also keep an eye on ostro-dev and changes, most of what is provided there should be offered by default in ostro sooner or later, like the automount handlers, network will be handled by connman... I guess we should also make the "warn" services board-dependent or just drop them, currently they try to use some pins which are specific to Calamari.

**Comment by mythi** [comment]
@barbieri:
v2: rename original soletta-systemd-files to soletta-demo-systemd-files

**Comment by brunobottazzini** [comment]
@barbieri alright will do

**Comment by mythi** [comment]
@barbieri @brunobottazzini is the naming now better?

**Comment by brunobottazzini** [comment]
@mythi LGTM

**Comment by brunobottazzini** [comment]
@mythi, try looking before why the ci check has failed

**Comment by mythi** [comment]
@brunobottazzini we believe test_edison error is a problem on the CI side...we're looking into it. This is  OK to accept without full pass.

**Comment by barbieri** [comment]
+1, just merge it

**Comment by mythi** [comment]
@brunobottazzini fyi, I pushed this too.

**Pull request merged**
