### PR TITLE
WIP: dev-app: add the missing multer dependency files manually

### PR DESCRIPTION
**Pull request by yongli3**
Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by anselmolsm** [comment]
Why not add multer to dev-app's package.json? Adding this .tar.gz to the repo does not seem the best approach IMO.

**Comment by yongli3** [comment]
@anselmolsm Please help to check, tt seems to me that the multer had been added into the package.json file as below, but I do not know why the standalone tar.gz does not include the multer module
commit 228634894e05c0df1fda0c9c729d47486a4ebfcf
Author: Kamidi Preetham kamidi@live.com
Date:   Thu Jun 2 01:24:51 2016 +0530

```
Added 'multer': middleware to handle form-data

Signed-off-by: Kamidi Preetham <kamidi@live.com>
```

**Comment by mythi** [comment]
-1

the standalone .tar.gz releases are manually created.

**Comment by yongli3** [comment]
@mythi Could you let me know how to generate this tar.gz file ?

**Comment by mythi** [comment]
@yongli3 @brunobottazzini knows

**Comment by peijiajames** [comment]
@ceolin @anselmolsm Do you know how dev-app tar.gz is created?

**Comment by anselmolsm** [comment]
@peijiajames No, I don't. And it is not documented, unfortunately...

**Comment by anselmolsm** [comment]
This tarball impacts images generation, as the recipe downloads it.
I generated a tarball and tagged v1_beta11 (https://github.com/solettaproject/soletta-dev-app/releases/tag/v1_beta11). Please test and let me know if it works.

Steps to generate this tarball:
Downloaded soletta-dev-app code (Github zip of master branch) && cd soletta-dev-app
npm install && bower install
cd .. && tar cf soletta-dev-app_standalone-test.tar.gz soletta-dev-app
- I noticed some warnings reported by npm, it's time to give some love to packages.json as well.
- why is this tarball bigger than the previous one (95MB x 25MB)?

**Comment by chongyic** [comment]
@anselmolsm 
@yongli3 
@fulong82

Tarball is bigger due to it is not compressed. tar cf as oppose to tar czf.
This fail on unpack during bitbake soletta-dev-app as the name ends with tar.gz but it's actually a tarball without compression.
Do we needs all other node modules as well?
This is the list of directory in node modules in previous release:
session-file-store
octonode
node-uuid
morgan
mocha
line-reader
express-session
express
expect.js
ejs
debug
cookie-parser
body-parser

**Comment by anselmolsm** [comment]
@chongyic definitely, I reused a tar line from my fish-shell history, without compression.  Now compressed it has ~~26MB~~ 29MB. Thanks for pointing that out.

The node modules list needs a review, indeed.

**Comment by yongli3** [comment]
Since  the https://github.com/solettaproject/soletta-dev-app/releases/download/v1_beta11/soletta-dev-app_standalone_v1_beta11-2.tar.gz file is okay, we can close this PR

**Pull request closed without merging**
